//! UI text table (Chinese default, English via `DBXT_LANG=en`).
//!
//! Every user-facing string in dbxt goes through [`t`] (plain) or [`tf`]
//! (templated). The Chinese literal is the key and the default; the English
//! translation lives here. Both are `&'static str`, so a lookup never allocates.

use std::fmt;
use std::sync::atomic::{AtomicU8, Ordering};

/// UI language.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Lang {
    Zh,
    En,
}

static LANG: AtomicU8 = AtomicU8::new(0);

/// Force the process-wide UI language (used at startup and by tests).
pub fn set_lang(l: Lang) {
    LANG.store(
        match l {
            Lang::Zh => 0,
            Lang::En => 1,
        },
        Ordering::Relaxed,
    );
}

/// Current process-wide UI language.
pub fn lang() -> Lang {
    if LANG.load(Ordering::Relaxed) == 1 {
        Lang::En
    } else {
        Lang::Zh
    }
}

/// Resolve the startup language: `DBXT_LANG` wins, then `LC_ALL` / `LC_MESSAGES`
/// / `LANG`. A `zh*` locale means Chinese; anything else means English; with
/// nothing set the built-in default is Chinese.
pub fn detect_lang() -> Lang {
    let dbxt = std::env::var_os("DBXT_LANG").map(|v| v.to_string_lossy().into_owned());
    let locale = ["LC_ALL", "LC_MESSAGES", "LANG"]
        .iter()
        .find_map(std::env::var_os)
        .map(|v| v.to_string_lossy().into_owned());
    detect_lang_from(dbxt.as_deref(), locale.as_deref())
}

/// Pure language resolution, split out so it can be tested without touching the
/// process environment.
pub fn detect_lang_from(dbxt: Option<&str>, locale: Option<&str>) -> Lang {
    if let Some(v) = dbxt {
        let v = v.to_ascii_lowercase();
        if v.starts_with("en") {
            return Lang::En;
        }
        if v.starts_with("zh") || v.starts_with("cn") {
            return Lang::Zh;
        }
        // Unknown explicit value: fall through to the locale.
    }
    if let Some(v) = locale {
        let v = v.to_ascii_lowercase();
        if v.starts_with("zh") || v.starts_with("cn") {
            return Lang::Zh;
        }
        if !v.is_empty() && v != "c" && v != "posix" {
            return Lang::En;
        }
    }
    Lang::Zh
}

/// Translate a plain UI string. Unknown keys fall back to the Chinese original.
pub fn t(zh: &'static str) -> &'static str {
    if lang() == Lang::Zh {
        return zh;
    }
    en_of(zh).unwrap_or(zh)
}

/// Translate against an explicit language (for snapshot tests).
#[allow(dead_code)]
pub fn t_lang(zh: &'static str, l: Lang) -> &'static str {
    if l == Lang::Zh {
        return zh;
    }
    en_of(zh).unwrap_or(zh)
}

/// Translate a template and substitute positional `{}` placeholders. `{{` / `}}`
/// are literal braces. Falls back to the Chinese template for unknown keys.
pub fn tf(zh: &'static str, args: &[&dyn fmt::Display]) -> String {
    render(t(zh), args)
}

/// Same as [`tf`] but with an explicit language (for snapshot tests).
#[allow(dead_code)]
pub fn tf_lang(zh: &'static str, args: &[&dyn fmt::Display], l: Lang) -> String {
    render(t_lang(zh, l), args)
}

fn render(tmpl: &str, args: &[&dyn fmt::Display]) -> String {
    use fmt::Write;
    let mut out = String::with_capacity(tmpl.len() + 16);
    let mut it = args.iter();
    let mut chars = tmpl.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '{' => {
                if chars.peek() == Some(&'{') {
                    chars.next();
                    out.push('{');
                } else if chars.peek() == Some(&'}') {
                    chars.next();
                    if let Some(a) = it.next() {
                        let _ = write!(out, "{a}");
                    }
                } else {
                    out.push('{');
                }
            }
            '}' => {
                if chars.peek() == Some(&'}') {
                    chars.next();
                }
                out.push('}');
            }
            _ => out.push(c),
        }
    }
    out
}


/// Every key the table knows, for coverage tests and tooling. Keep in sync with
/// [`en_of`] (a test asserts each entry resolves to a distinct English string).
#[allow(dead_code)]
pub static ALL_KEYS: &[&str] = &[
    " Redis db · ↑↓ Enter · Esc 关 ",
    " SQL 片段 · {} 个 · Enter 插入 · r 刷新 · Esc 关 ",
    " WHERE 过滤 · Enter 应用 · Esc 取消 · 留空清除 ",
    " {} · {}/{} · Esc 关闭 ",
    " {} 表 {}/{} ",
    " {}{}.{} · 第 {} 页 · {}–{} / {} · {}{}{} ",
    " {}结果 {}/{} · {} · {} · [ ] 切换 ",
    " {}结果 · {} ",
    " {}语句 {} 结果 · {} · Esc 返回脚本 ",
    " · n 下一页",
    " · 排序: {}",
    " · 点击/Ctrl-W 展开",
    " · 过滤: {}",
    " ⚠ 危险操作确认 ",
    " ✎ 编辑 {}.{} ",
    " ➕ 插入 {}.{} ",
    " 列显示 {}/{} · 空格勾选 · a 全选 · x 仅首列 · Esc 关 ",
    " 快捷键 · {}/{} · ↑↓ 滚动 · Esc 关闭 ",
    " 搜索结果 {} 行命中 · Enter 保留 · Esc 清除 ",
    " 收藏为 SQL 片段（DBX saved_sql_files）· Enter 保存 · Esc 取消 ",
    " 数据库 · ↑↓ Enter · Esc 关 ",
    " 新值 · Enter 执行 ",
    " 新建连接 ",
    " 最近表 · ↑↓ Enter 直达 · Esc 关 ",
    " 结果 ",
    " 脚本 · {} 条语句 · 影响 {} 行 · {} 错误 · Enter 查看结果 ",
    " 补全 · T表 C列 K关键字 · Tab 上屏 · ↑↓ · Esc ",
    " 表结构 (DDL) · {} · {}/{} 行 · t 返回字段 ",
    " 表结构 · {} · {} · t 查看 DDL ",
    " 输出 ",
    " 过滤表名 {}/{} · Enter 保留 · Esc 清除 ",
    " 连接 ",
    " 连接 · ↑↓ Enter · c 新建 · p 复制 · q 隐藏 ",
    " 鼠标事件 DBXT_MOUSE_DEBUG · 横滑={} ",
    "-- 无法获取 DDL: {}",
    "/ 过滤表名",
    "DELETE 不可撤销，Enter 后立即执行",
    "DELETE 没有 WHERE 子句，会作用于整张表",
    "DROP 会永久删除对象",
    "EXPLAIN 当前 SQL（SQL 后端）",
    "Enter 执行 · Esc 取消 · Ctrl-V 转编辑器 · Ctrl-T 加入批量",
    "Enter/y 执行   Esc/n 取消",
    "MongoDB 切库",
    "MySQL 反引号 `col` · PG 双引号 \"col\"（区分大小写）",
    "Redis 固定 16 个逻辑库",
    "Redis 逻辑库",
    "SQL … (Ctrl-J / F5 执行 · ↑ 历史)",
    "SQL ▸ {} · 点击/Tab 展开",
    "SQL ▸ 空 · 点击/Tab 展开",
    "SQL 前缀补全（表名 T / 列名 C / 关键字 K，Tab 上屏）",
    "SQL 片段收藏（DBX saved_sql_files）",
    "Shift/Alt/Ctrl+滚轮 · 横滑",
    "TRUNCATE 会清空整张表且不可回滚",
    "WHERE 恒真（1 = 1），会作用于整张表",
    "WHERE 过滤（预填当前列）",
    "mongo parse: {} (例: db.col.find({{}}))",
    "mongo shell… (db={}) · Ctrl-L 切换",
    "name / host 必填",
    "q 显示\n连接列表",
    "q 显示连接列表",
    "redis db {} · d 切换",
    "redis 命令… (db={}) · Ctrl-L 切换",
    "stdout 不是终端，无法启动 TUI（--help / --version 可在管道中使用）",
    "{} (副本)",
    "{} · d 切换",
    "{} · 列宽≤{} 自适应，尽量一屏放下（Alt-C / w 关闭）",
    "{} · 列宽按内容（Alt-C / w 开启）",
    "{} · 已刷新当前页",
    "{} · 已刷新（第 {} 页）",
    "{} · 第 {} 行 · {} 字符",
    "{} 不支持单语句 EXPLAIN（请手动执行）",
    "{} 个 SQL 片段 · Enter 插入编辑器 · s 收藏当前 SQL · r 刷新 · Esc 关闭",
    "{} 个表/视图",
    "{} 个表/视图 · Enter 数据 · r 结构 · / 过滤 · Tab 编辑SQL",
    "{} 个连接 · ↑↓+Enter 选择 · c 新建",
    "{} 字段",
    "{} 没有 WHERE 子句，会作用于整张表",
    "{} 结构 · {} 字段 · t 切换 DDL · Esc 返回",
    "{} 行",
    "{}.{} · 第 {} 页 · {} 行 · {}{}",
    "— SQL 片段（Ctrl-O）—",
    "— 侧栏 —",
    "— 全局 —",
    "— 危险操作 / 删除确认 —",
    "— 显示约定 —",
    "— 结果（表格浏览）—",
    "— 编辑器 / 命令 —",
    "— 编辑确认层 —",
    "— 连接选择 —",
    "…（语句过长，已截断显示）",
    "↑↓ 选表 · Enter 浏览数据 · r 表结构\nTab 到 SQL 编辑器 · Ctrl-L 切 redis/mongo 命令行",
    "↵ 保存连接",
    "▸ {} · {} 表",
    "▸ 未连接",
    "◀ ▶（底部）",
    "⚠ 未检测到主键：WHERE 用全部列匹配，请确认条件唯一",
    "⚠ 未检测到主键：将按全部列匹配删除，请确认只命中这一行",
    "✓ 已复制 INSERT（{} 字符）· OSC52 剪贴板",
    "✓ 已复制 INSERT（{} 字符）· OSC52 剪贴板 · 兜底 {}",
    "✓ 已导出 {} 行 → {}",
    "✓ 已插入 {}",
    "✓ 已收藏 SQL 片段「{}」（DBX saved_sql_files）",
    "✓ 影响 {} 行 · {}",
    "✓ 批量提交成功 · {} 条语句 · 影响 {} 行",
    "✗ use 需要数据库名",
    "✗ 导出失败: {}",
    "✗ 批量提交失败 · {} 错误 · 影响 {} 行（事务可能已回滚）· Enter 看详情",
    "✗ 数据库 {} 不在当前连接中",
    "✗ 未找到表 {}",
    "✗ 未找到表 {}（可能被过滤或已删除）",
    "✗ 未选择连接",
    "上屏",
    "下一区",
    "下一页 / 上一页",
    "主键 ",
    "事件 {}",
    "仅 1 个结果标签",
    "仅保留第一列（已记住）",
    "仅表格浏览支持删除行",
    "仅表格浏览支持快速插入",
    "仅表格浏览支持排序",
    "仅表格浏览支持过滤",
    "仅首列",
    "任一语句失败则整体回滚；Enter 后立即执行",
    "例: city = 'Beijing'（留空回车 = 清除）",
    "侧栏",
    "保存",
    "保存片段 {} …",
    "保存连接…",
    "保留",
    "先按 / 搜索结果，再用 n/N 跳转命中",
    "先选中一张表",
    "先选择连接",
    "全选",
    "全部 {} 列已适配",
    "共 {} 行",
    "关",
    "关闭",
    "切库",
    "切换",
    "切换到 {} …",
    "切换到 {} 并打开 {} …",
    "切换命令模式 SQL → Redis → MongoDB",
    "切换数据库 → {}",
    "切换数据库（快捷）",
    "切换本次会话的结果标签",
    "列",
    "列   ",
    "列 {}{}-{}/{}",
    "列显隐浮层（空格勾选 / a 全选 / x 仅首列，按 库.表 记住）",
    "列显隐：空格勾选显示的列（按 库.表 记住，跨会话）",
    "列窗口横滚一列（任意区域，按住连滚）",
    "删行",
    "删除当前行 → 确认后执行",
    "删除确认 · Enter 执行 · Esc 取消",
    "刷新",
    "刷新 / 关闭",
    "刷新数据库列表…",
    "加入批量",
    "加入批量队列（Ctrl-S 打包事务提交）",
    "加载 SQL 片段…",
    "加载 {} 第 {} 页…",
    "加载 {} 结构…",
    "加载 {} 表…",
    "加载 {}.{} 数据…",
    "加载更多… (上限 {} 行)",
    "加载连接…",
    "勾选",
    "升序",
    "单元格光标（列窗口跟随）",
    "历史",
    "历史（首行 / 末行）",
    "取消",
    "取消编辑",
    "可空",
    "启动时显示鼠标事件浮层（滑动无效时排查终端编码）",
    "回到侧栏",
    "复制",
    "复制INSERT",
    "复制当前行为 INSERT 语句（OSC52 + 文件兜底）",
    "复制连接 {} · 改参数后 Enter 保存",
    "复制连接（预填表单）",
    "字段",
    "字段 ↔ DDL（表结构）",
    "完整单元格（任意模式）",
    "导出当前结果为 CSV（$HOME）",
    "将删除 1 行（主键 {}）",
    "将生成的 SQL 转入编辑器微调",
    "已保存: {} ({})",
    "已刷新 {} 个数据库",
    "已加入批量队列（{} 条）· Ctrl-S 打包提交 · Ctrl-X 清空",
    "已取消",
    "已取消收藏",
    "已取消编辑",
    "已取消过滤",
    "已展开{}",
    "已截断",
    "已收起{}",
    "已显示全部列（已记住）",
    "已清空批量队列（{} 条）",
    "已清除结果搜索",
    "已清除表过滤 · {} 个表/视图",
    "已经是最后一页",
    "已经是第一页",
    "已转入编辑器微调 · Ctrl-J 执行",
    "已达上限 {} 行，请用 WHERE / LIMIT 缩小查询",
    "帮助",
    "应用",
    "底部进度条",
    "开",
    "强制 NULL 仅用灰色，不依赖终端斜体",
    "当前列窗口位置 · 点击可跳转",
    "当前无过滤条件",
    "当前视图不支持列选择",
    "影响 {} 行",
    "循环切换区域（侧栏 → 编辑器 → 结果）",
    "快速插入 → diff 确认后执行",
    "总数未知",
    "手动",
    "打开 DBX 存储文件失败 ({}): {}\n(可用 DBX_DATA_DIR 指定目录，或把 dbx.db 文件路径作为第一个位置参数传入)",
    "执行",
    "执行中…",
    "执行当前 SQL",
    "执行（SQL 全文可见）",
    "执行（UPDATE / INSERT，SQL 全文可见）",
    "批量 {} 待提交",
    "批量事务：{} 条修改将在同一个 BEGIN … COMMIT 中执行",
    "批量提交确认（{} 条）· Enter 执行 · Esc 取消",
    "批量队列为空（编辑时按 Ctrl-T 加入）",
    "把编辑器里的 SQL 收藏为片段（写入 DBX saved_sql_files）",
    "折叠 / 展开连接列表",
    "按 {} {}{}",
    "按当前列升 / 降序",
    "换模式",
    "换行",
    "提交 / 清空批量队列",
    "插入",
    "插入 {} → Enter 确认执行 · Esc 取消 · Ctrl-V 转编辑器 · Ctrl-T 加入批量",
    "插入层 v / b",
    "插入编辑器",
    "搜索",
    "搜索「{}」· 0 行命中",
    "搜索「{}」· {} 行命中",
    "搜索「{}」· {} 行命中 · n/N 跳转 · Esc 清除",
    "搜索「{}」· 命中 {}/{}",
    "搜索命中时：下 / 上一个命中（否则 n 翻页）",
    "搜索本页结果行…",
    "搜索结果行（输入即筛选，Enter 保留，Esc 清除）",
    "操作超时（{}s）· 服务器无响应或网络中断，请检查连接后用 d 重连",
    "收藏",
    "收起 / 展开当前焦点区域",
    "收起结果 / 关闭浮层",
    "数据库列表（浮层内 r 刷新）",
    "整屏滚动，跨页衔接",
    "整行详情（紧凑列模式）/ 完整单元格",
    "整行详情（纵向，含隐藏列）",
    "新增一行到 {}.{}",
    "新建",
    "新建连接",
    "无可补全项（前缀「{}」）",
    "无法从当前结果确定表名（仅表格浏览与含 FROM 的查询支持 y）",
    "无法列举数据库（{}），仅使用配置库 {}",
    "无法列举数据库（{}），将使用连接默认库",
    "无表 · Tab 到 SQL 编辑器 · Ctrl-L 切 redis/mongo 命令行",
    "旧值 ",
    "显示列 {} · 已记住",
    "显隐",
    "最近浏览的 5 张表，Enter 直达（侧栏 t）",
    "最近表浮层（Enter 直达）",
    "最近表直达浮层",
    "未发现数据库",
    "未知类型: {} (mysql / postgres / redis / mongodb …)",
    "未知选项: {}",
    "未连接",
    "本帮助",
    "横向滚动列（触屏左右滑动 / 拖动）；PC 终端若 Shift+滚轮 无效，用 Ctrl+滚轮 或 Ctrl-G",
    "横滚 关 · 滚轮纵向",
    "横滚 开",
    "横滚 开 · 滚轮横滚列",
    "横滚列一列（任意区域，按住连滚）",
    "横滚模式（触屏兜底：滚轮/上下滑 = 横滚列）",
    "横滚模式：纵向滚轮/上下滑改为横滚列",
    "没有保存的 SQL 片段（可在 DBX 桌面端保存后复用）",
    "没有可切换的数据库",
    "没有可删除的行",
    "没有可加载的更多结果（结果未截断）",
    "没有可复制的行",
    "没有可导出的列",
    "没有可导出的结果",
    "没有可插入的列",
    "没有可搜索的结果",
    "没有可选择的列（先打开一张表或执行查询）",
    "注释",
    "浏览",
    "浏览表数据",
    "清除",
    "清除过滤",
    "滚动",
    "点击向左/右翻一屏列（触屏可用）",
    "焦点 SQL",
    "焦点 侧栏",
    "焦点 命令",
    "焦点 结果",
    "片段名称不能为空",
    "生成的 SQL（Enter 执行）",
    "留空 = NULL · '文本' = 字符串",
    "直接聚焦 侧栏 / 编辑器 / 结果",
    "直达",
    "真正的 SQL NULL：灰色斜体（终端不支持斜体时仅灰色）",
    "移动表列表",
    "空字符串：灰色，带引号的空串，不会与 NULL 混淆",
    "第 {} 行 · {} 列",
    "第 {}/{} 页",
    "类型",
    "紧凑列",
    "紧凑列 {}{}",
    "紧凑列 手动",
    "紧凑列宽 开 / 关（窄屏默认自动开，按 库.表 记住）",
    "紧凑列宽：窄屏自动共享列宽，宽表尽量一屏放下",
    "结构",
    "结果",
    "结果 {}/{}",
    "结果 ▸ {} 行 · 点击/Ctrl-W 展开",
    "结果区",
    "结果搜索已清除",
    "结果被截断时加载更多行",
    "编辑",
    "编辑 {} → Enter 确认执行 · Esc 取消 · Ctrl-V 转编辑器 · Ctrl-T 加入批量",
    "编辑/保存",
    "编辑单元格 → diff 确认后执行",
    "编辑器",
    "编辑器为空：先写 SQL 再收藏",
    "耗时",
    "聚焦 SQL 编辑器",
    "脚本 {} 条",
    "脚本 · {} 条语句 · 影响 {} 行 · {} 错误 · Enter 看结果",
    "脚本列表不支持搜索（先 Enter 进入某条语句的结果）",
    "脚本列表没有可复制的行（先 Enter 进入某条语句的结果）",
    "自动",
    "自动折叠 关",
    "自动折叠 开",
    "自动折叠 开 / 关（开=非焦点栏收起）",
    "自动折叠：关 · 所有栏展开（Ctrl-A 开启）",
    "自动折叠：开 · 非焦点栏收起（Ctrl-A 关闭）",
    "至少保留一列",
    "行",
    "行 {}/{}",
    "行光标（到边自动翻页）",
    "补全",
    "补全上下文",
    "表",
    "表名. 后只补该表列名；FROM/JOIN 后优先表名；WHERE/ON 后优先列名",
    "表结构尚未加载，稍后重试",
    "表结构视图不支持搜索",
    "表结构视图没有可复制的数据行",
    "表结构（字段 + DDL）",
    "详情",
    "语句",
    "语法: = != <> > < >= <= LIKE IN BETWEEN IS NULL · AND/OR · 字符串单引号",
    "转编辑器",
    "转编辑器 / 加入批量（等价 Ctrl-V / Ctrl-T）",
    "输入以搜索结果行…",
    "过滤",
    "过滤: {}",
    "过滤「{}」· {}/{} 个表 · Esc 清除",
    "过滤已清除",
    "过滤表名（输入即筛选，Enter 保留，Esc 清除）",
    "运行",
    "返回",
    "返回连接选择",
    "还没有浏览过表",
    "还没有表可过滤",
    "连接",
    "连接 {} ({})…",
    "退出",
    "选择",
    "选择 / 插入到编辑器",
    "选择 / 连接",
    "选择连接",
    "钉住 / 取消首列",
    "键",
    "附加排序键（多列排序）",
    "降序",
    "隐藏列 {}",
    "隐藏列 {} · 已记住",
    "首列已取消钉住 · z 钉住",
    "首列已钉住 · z 取消",
    "首行 / 末行",
    "默认值",
    "（附加排序键）",
    "🔍「{}」{} 命中 · ",
    // CLI help (`dbxt --help`)
    "  DBX_STORE  dbx.db 文件或其所在目录（默认：DBX_DATA_DIR 或平台默认位置）",
    "  -h, --help     显示本帮助",
    "  -V, --version  显示版本",
    "DBX 的终端界面",
    "参数",
    "文档",
    "选项",
    "用法",
    " · 已截断",
    " · 更多",
    "（暂不支持的类型）",
    "永不过期",
    "不存在",
    "重新扫描 keys…",
    "先选中一个 key",
    "例: app:*（留空回车 = 全部 *）",
    "key 匹配模式（SCAN MATCH）",
    "秒数（-1 = 持久化，0 = 立即删除）",
    "该类型暂不支持直接编辑，可用命令行修改",
    "DEL 不可撤销，Enter 后立即执行",
    "JSON 过滤，例: {\"age\": {\"$gt\": 30}}（留空 = 全部）",
    "Enter 执行 · Esc 取消",
    "确认写入 · Enter 执行 · Esc 取消",
    "匹配模式",
    "查看值",
    "更多",
    "重扫",
    "逻辑库",
    "命令台",
    "重命名",
    "删 key",
    "翻页",
    "JSON 过滤",
    "无 key · Tab 到命令台 · / 匹配模式 · r 重扫",
    "↑↓ 选 key · Enter 查看值 · n 更多 · / 匹配模式\nTab 到命令台 · Ctrl-L 切换模式",
    " 文档 ",
    "/ 匹配模式（SCAN MATCH）",
    "  n 加载更多…",
    "  （无匹配 key）",
    "SCAN MATCH 模式，例 app:* · 支持 * ? []",
    "秒数；-1 = 持久化，0 = 立即删除",
    "新 key 名（已存在的 key 会被覆盖）",
    "新的 string 内容（支持多行）",
    "新的 hash 字段值",
    " MongoDB 过滤 (JSON) · Enter 应用 · Esc 取消 · 留空清除 ",
    "运算符: $eq $gt $lt $in $regex $exists · 留空 = 全部",
    "{} 字节",
    "{} 个元素",
    "{} 个成员",
    "{} 个字段",
    "{} 条",
    "{} 个文档",
    "{} 个索引",
    "加载 {} keys…",
    "{} 个 key · 已全部加载",
    "{} 个 key · 已加载 {} · n 加载更多",
    "{}.{} · 第 {} 页 · {} 个文档 · 共 {} · n/p 翻页 · f 过滤",
    "{} 索引 · {} · Esc 返回",
    "加载 {} 索引…",
    "加载 key {}…",
    "加载 {} 文档…",
    "设置 TTL · {}",
    "重命名 key · {}",
    "编辑 string · {}",
    "编辑 hash 字段 · {} · {}",
    "redis db {} · {} keys · d 切换",
    "执行 {}…",
    "✓ 已复制（{} 字符）· 兜底 {}",
    "✓ 已复制（{} 字符）· OSC52 剪贴板",
    "将删除 key {}（不可撤销）",
    "匹配模式 → {}",
    "将执行 {}",
    " {}Redis · {} · {} · TTL {} · {} · e 编辑 x TTL m 重命名 Del 删除 ",
    "共 {} 个",
    " · 过滤 {}",
    "Enter 确认 · Esc 取消",
    " · 更多（n 加载）",
    "已全部加载",
    "加载更多…",
    "已加载 {} 项",
    "已加载 {} 项 · 全部",
    "已加载 {} 项 · n 继续",
    "— Redis key 浏览器 —",
    "— MongoDB 文档浏览器 —",
    "选择 key / 查看 value",
    "编辑 SCAN MATCH 模式（留空 = 全部）",
    "加载下一 SCAN 页",
    "以当前模式重扫",
    "切换逻辑 db",
    "编辑 string·hash 字段 / TTL / 重命名 / 删除 key（均确认）",
    "大集合继续加载 200 项",
    "复制当前行为 TSV",
    "浏览 collection 文档（JSON 网格）",
    "文档翻页",
    "JSON 过滤（如 {\"age\": {\"$gt\": 30}}，留空清除）",
    "查看 collection 索引",
    "查看 collection 索引",
    "已选 {}",
    "已选 {} 个 key",
    "已全选 {} 个 key",
    "已清除选择",
    "{} · {} keys · 已选 {} ",
    "✓ 已复制 {} 个 key 名 · 兜底 {}",
    "✓ 已复制 {} 个 key 名 · OSC52 剪贴板",
    "批量执行 {} 条命令…",
    "批量完成 {}/{}：{}",
    "✓ 批量完成 {}/{} 条命令",
    "将影响 {} 个 key（模式 {}）",
    "Enter 后按顺序执行，不可撤销",
    "批量确认 · Enter 执行 · Esc 取消",
    "选中 {} 个 key 超过单页上限 {}，请分批操作（space 取消部分选择）",
    "批量删除 {} 个 key",
    "将批量删除 {} 个 key（模式 {}）",
    "… 其余 {} 条命令",
    "共 {} 个 key · {} 条命令",
    "批量设置 TTL · {} 个 key",
    "批量设置 TTL={}s · {} 个 key",
    "将对 {} 个 key 设置 TTL={}s（模式 {}）",
    "Enter 后立即执行",
    "TTL 需为整数秒（-1 持久化，0 立即删除）",
    "旧前缀=新前缀，例: app: = new:",
    "旧前缀=新前缀，例 app: = new:",
    "格式：旧前缀=新前缀，例 app: = new:",
    "批量前缀重命名 · {} 个 key",
    "批量前缀重命名 {} → {} · {} 个 key",
    "将重命名 {} 个 key：{} → {}（模式 {}）",
    "没有 key 匹配该前缀（未改名）",
    "没有可操作的 key",
    "勾选 key / 范围选（a 全选已加载）",
    "批量删除 / 设 TTL / 前缀重命名选中 key（均确认）",
    "复制选中的 key 名（每行一个）",
    "编辑 / 插入 / 删除文档（均确认，_id 不可改）",
    "二次确认 · {}",
    "输入 {} 或 YES",
    "二次确认：输入 {} 或 YES",
    "输入不匹配（需 {} 或 YES）",
    "输入 key 数或 YES 以确认删除",
    "没有可编辑的文档",
    "没有可删除的文档",
    "JSON 文档（_id 不可修改）",
    "新文档 JSON（省略 _id 则由 MongoDB 生成）",
    "编辑文档 · Ctrl-S 校验并保存 · Esc 取消",
    "插入文档 · Ctrl-S 校验并保存 · Esc 取消",
    "将删除文档 _id={}（不可撤销）",
    "删除文档确认 · Enter 执行 · Esc 取消",
    "JSON 非法：{}",
    "✗ JSON 非法：{}",
    "文档必须是 JSON 对象 { … }",
    "✗ 文档必须是 JSON 对象",
    "将向 {}.{} 插入 1 个文档",
    "插入确认 · Enter 执行 · Esc 取消",
    "_id 不可修改（请恢复原值）",
    "✗ _id 不可修改",
    "（没有字段变化）",
    "…（更多字段已省略）",
    "将替换文档 _id={}",
    "更新确认（含 diff）· Enter 执行 · Esc 取消",
    "_id 不可修改 · Ctrl-S 预览 diff 后确认",
    "输入 JSON 对象，可省略 _id",
    "Ctrl-S 校验并保存 · Esc 取消 · 方向键移动",
    " ✎ 编辑文档 {}.{} ",
    " ➕ 插入文档 {}.{} ",
    "批量删",
    "批量TTL",
    "批量改名",
    "删文档",
    "校验并保存",
];

/// The Chinese → English table. Keys must match the source literals exactly.
fn en_of(zh: &'static str) -> Option<&'static str> {
    match zh {
        " Redis db · ↑↓ Enter · Esc 关 " => Some(" Redis db · ↑↓ Enter · Esc close "),
        " SQL 片段 · {} 个 · Enter 插入 · r 刷新 · Esc 关 " => Some(" SQL snippets · {} · Enter insert · r refresh · Esc close "),
        " WHERE 过滤 · Enter 应用 · Esc 取消 · 留空清除 " => Some(" WHERE filter · Enter apply · Esc cancel · empty clears "),
        " {} · {}/{} · Esc 关闭 " => Some(" {} · {}/{} · Esc close "),
        " {} 表 {}/{} " => Some(" {} tables {}/{} "),
        " {}{}.{} · 第 {} 页 · {}–{} / {} · {}{}{} " => Some(" {}{}.{} · page {} · {}–{} / {} · {}{}{} "),
        " {}结果 {}/{} · {} · {} · [ ] 切换 " => Some(" {}results {}/{} · {} · {} · [ ] switch "),
        " {}结果 · {} " => Some(" {}results · {} "),
        " {}语句 {} 结果 · {} · Esc 返回脚本 " => Some(" {}stmts {} results · {} · Esc back to script "),
        " · n 下一页" => Some(" · n next page"),
        " · 排序: {}" => Some(" · sort: {}"),
        " · 点击/Ctrl-W 展开" => Some(" · click/Ctrl-W expand"),
        " · 过滤: {}" => Some(" · filter: {}"),
        " ⚠ 危险操作确认 " => Some(" ⚠ Confirm dangerous operation "),
        " ✎ 编辑 {}.{} " => Some(" ✎ Edit {}.{} "),
        " ➕ 插入 {}.{} " => Some(" ➕ Insert {}.{} "),
        " 列显示 {}/{} · 空格勾选 · a 全选 · x 仅首列 · Esc 关 " => Some(" columns {}/{} · Space toggle · a all · x first only · Esc close "),
        " 快捷键 · {}/{} · ↑↓ 滚动 · Esc 关闭 " => Some(" shortcuts · {}/{} · ↑↓ scroll · Esc close "),
        " 搜索结果 {} 行命中 · Enter 保留 · Esc 清除 " => Some(" results search {} hits · Enter keep · Esc clear "),
        " 收藏为 SQL 片段（DBX saved_sql_files）· Enter 保存 · Esc 取消 " => Some(" Save as SQL snippet (DBX saved_sql_files) · Enter save · Esc cancel "),
        " 数据库 · ↑↓ Enter · Esc 关 " => Some(" databases · ↑↓ Enter · Esc close "),
        " 新值 · Enter 执行 " => Some(" new value · Enter execute "),
        " 新建连接 " => Some(" New connection "),
        " 最近表 · ↑↓ Enter 直达 · Esc 关 " => Some(" recent tables · ↑↓ Enter jump · Esc close "),
        " 结果 " => Some(" results "),
        " 脚本 · {} 条语句 · 影响 {} 行 · {} 错误 · Enter 查看结果 " => Some(" script · {} statements · {} rows affected · {} errors · Enter view results "),
        " 补全 · T表 C列 K关键字 · Tab 上屏 · ↑↓ · Esc " => Some(" completion · T tables C columns K keywords · Tab accept · ↑↓ · Esc "),
        " 表结构 (DDL) · {} · {}/{} 行 · t 返回字段 " => Some(" structure (DDL) · {} · {}/{} rows · t back to fields "),
        " 表结构 · {} · {} · t 查看 DDL " => Some(" structure · {} · {} · t view DDL "),
        " 输出 " => Some(" output "),
        " 过滤表名 {}/{} · Enter 保留 · Esc 清除 " => Some(" filter tables {}/{} · Enter keep · Esc clear "),
        " 连接 " => Some(" connections "),
        " 连接 · ↑↓ Enter · c 新建 · p 复制 · q 隐藏 " => Some(" connections · ↑↓ Enter · c new · p duplicate · q hide "),
        " 鼠标事件 DBXT_MOUSE_DEBUG · 横滑={} " => Some(" mouse events DBXT_MOUSE_DEBUG · drag={} "),
        "-- 无法获取 DDL: {}" => Some("-- cannot fetch DDL: {}"),
        "/ 过滤表名" => Some("/ filter tables"),
        "DELETE 不可撤销，Enter 后立即执行" => Some("DELETE cannot be undone; runs immediately on Enter"),
        "DELETE 没有 WHERE 子句，会作用于整张表" => Some("DELETE has no WHERE clause and will affect the whole table"),
        "DROP 会永久删除对象" => Some("DROP permanently deletes the object"),
        "EXPLAIN 当前 SQL（SQL 后端）" => Some("EXPLAIN current SQL (SQL backends)"),
        "Enter 执行 · Esc 取消 · Ctrl-V 转编辑器 · Ctrl-T 加入批量" => Some("Enter execute · Esc cancel · Ctrl-V to editor · Ctrl-T add to batch"),
        "Enter/y 执行   Esc/n 取消" => Some("Enter/y execute   Esc/n cancel"),
        "MongoDB 切库" => Some("MongoDB switch database"),
        "MySQL 反引号 `col` · PG 双引号 \"col\"（区分大小写）" => Some("MySQL backtick `col` · PG double quote \"col\" (case sensitive)"),
        "Redis 固定 16 个逻辑库" => Some("Redis has a fixed 16 logical databases"),
        "Redis 逻辑库" => Some("Redis logical database"),
        "SQL … (Ctrl-J / F5 执行 · ↑ 历史)" => Some("SQL … (Ctrl-J / F5 run · ↑ history)"),
        "SQL ▸ {} · 点击/Tab 展开" => Some("SQL ▸ {} · click/Tab expand"),
        "SQL ▸ 空 · 点击/Tab 展开" => Some("SQL ▸ empty · click/Tab expand"),
        "SQL 前缀补全（表名 T / 列名 C / 关键字 K，Tab 上屏）" => Some("SQL prefix completion (T table / C column / K keyword, Tab accept)"),
        "SQL 片段收藏（DBX saved_sql_files）" => Some("SQL snippet library (DBX saved_sql_files)"),
        "Shift/Alt/Ctrl+滚轮 · 横滑" => Some("Shift/Alt/Ctrl+wheel · drag"),
        "TRUNCATE 会清空整张表且不可回滚" => Some("TRUNCATE empties the whole table and cannot be rolled back"),
        "WHERE 恒真（1 = 1），会作用于整张表" => Some("WHERE is always true (1 = 1) and will affect the whole table"),
        "WHERE 过滤（预填当前列）" => Some("WHERE filter (prefilled with current column)"),
        "mongo parse: {} (例: db.col.find({{}}))" => Some("mongo parse: {} (e.g. db.col.find({{}}))"),
        "mongo shell… (db={}) · Ctrl-L 切换" => Some("mongo shell… (db={}) · Ctrl-L switch"),
        "name / host 必填" => Some("name / host required"),
        "q 显示\n连接列表" => Some("q show\nconnection list"),
        "q 显示连接列表" => Some("q show connection list"),
        "redis db {} · d 切换" => Some("redis db {} · d switch"),
        "redis 命令… (db={}) · Ctrl-L 切换" => Some("redis command… (db={}) · Ctrl-L switch"),
        "stdout 不是终端，无法启动 TUI（--help / --version 可在管道中使用）" => Some("stdout is not a terminal, cannot start the TUI (--help / --version work over a pipe)"),
        "{} (副本)" => Some("{} (copy)"),
        "{} · d 切换" => Some("{} · d switch"),
        "{} · 列宽≤{} 自适应，尽量一屏放下（Alt-C / w 关闭）" => Some("{} · width ≤{} shared so the table fits (Alt-C / w off)"),
        "{} · 列宽按内容（Alt-C / w 开启）" => Some("{} · content-sized columns (Alt-C / w on)"),
        "{} · 已刷新当前页" => Some("{} · current page refreshed"),
        "{} · 已刷新（第 {} 页）" => Some("{} · refreshed (page {})"),
        "{} · 第 {} 行 · {} 字符" => Some("{} · row {} · {} chars"),
        "{} 不支持单语句 EXPLAIN（请手动执行）" => Some("{} does not support single-statement EXPLAIN (run it manually)"),
        "{} 个 SQL 片段 · Enter 插入编辑器 · s 收藏当前 SQL · r 刷新 · Esc 关闭" => Some("{} SQL snippets · Enter insert into editor · s save current SQL · r refresh · Esc close"),
        "{} 个表/视图" => Some("{} tables/views"),
        "{} 个表/视图 · Enter 数据 · r 结构 · / 过滤 · Tab 编辑SQL" => Some("{} tables/views · Enter data · r structure · / filter · Tab edit SQL"),
        "{} 个连接 · ↑↓+Enter 选择 · c 新建" => Some("{} connections · ↑↓+Enter select · c new"),
        "{} 字段" => Some("{} fields"),
        "{} 没有 WHERE 子句，会作用于整张表" => Some("{} has no WHERE clause and will affect the whole table"),
        "{} 结构 · {} 字段 · t 切换 DDL · Esc 返回" => Some("{} structure · {} fields · t toggle DDL · Esc back"),
        "{} 行" => Some("{} rows"),
        "{}.{} · 第 {} 页 · {} 行 · {}{}" => Some("{}.{} · page {} · {} rows · {}{}"),
        "— SQL 片段（Ctrl-O）—" => Some("— SQL snippets (Ctrl-O) —"),
        "— 侧栏 —" => Some("— Sidebar —"),
        "— 全局 —" => Some("— Global —"),
        "— 危险操作 / 删除确认 —" => Some("— Dangerous / delete confirmation —"),
        "— 显示约定 —" => Some("— Display conventions —"),
        "— 结果（表格浏览）—" => Some("— Results (table browsing) —"),
        "— 编辑器 / 命令 —" => Some("— Editor / command —"),
        "— 编辑确认层 —" => Some("— Edit confirmation —"),
        "— 连接选择 —" => Some("— Connection picker —"),
        "…（语句过长，已截断显示）" => Some("…(statement too long, truncated)"),
        "↑↓ 选表 · Enter 浏览数据 · r 表结构\nTab 到 SQL 编辑器 · Ctrl-L 切 redis/mongo 命令行" => Some("↑↓ pick table · Enter browse data · r structure\nTab to SQL editor · Ctrl-L switch redis/mongo shell"),
        "↵ 保存连接" => Some("↵ Save connection"),
        "▸ {} · {} 表" => Some("▸ {} · {} tables"),
        "▸ 未连接" => Some("▸ Not connected"),
        "◀ ▶（底部）" => Some("◀ ▶ (bottom)"),
        "⚠ 未检测到主键：WHERE 用全部列匹配，请确认条件唯一" => Some("⚠ No primary key detected: WHERE matches all columns, make sure the condition is unique"),
        "⚠ 未检测到主键：将按全部列匹配删除，请确认只命中这一行" => Some("⚠ No primary key detected: DELETE matches all columns, make sure only this row is hit"),
        "✓ 已复制 INSERT（{} 字符）· OSC52 剪贴板" => Some("✓ Copied INSERT ({} chars) · OSC52 clipboard"),
        "✓ 已复制 INSERT（{} 字符）· OSC52 剪贴板 · 兜底 {}" => Some("✓ Copied INSERT ({} chars) · OSC52 clipboard · fallback {}"),
        "✓ 已导出 {} 行 → {}" => Some("✓ Exported {} rows → {}"),
        "✓ 已插入 {}" => Some("✓ Inserted {}"),
        "✓ 已收藏 SQL 片段「{}」（DBX saved_sql_files）" => Some("✓ Saved SQL snippet \"{}\" (DBX saved_sql_files)"),
        "✓ 影响 {} 行 · {}" => Some("✓ {} rows affected · {}"),
        "✓ 批量提交成功 · {} 条语句 · 影响 {} 行" => Some("✓ Batch committed · {} statements · {} rows affected"),
        "✗ use 需要数据库名" => Some("✗ use requires a database name"),
        "✗ 导出失败: {}" => Some("✗ Export failed: {}"),
        "✗ 批量提交失败 · {} 错误 · 影响 {} 行（事务可能已回滚）· Enter 看详情" => Some("✗ Batch commit failed · {} errors · {} rows affected (transaction may have rolled back) · Enter for details"),
        "✗ 数据库 {} 不在当前连接中" => Some("✗ Database {} is not in the current connection"),
        "✗ 未找到表 {}" => Some("✗ Table {} not found"),
        "✗ 未找到表 {}（可能被过滤或已删除）" => Some("✗ Table {} not found (filtered out or dropped)"),
        "✗ 未选择连接" => Some("✗ No connection selected"),
        "上屏" => Some("accept"),
        "下一区" => Some("next pane"),
        "下一页 / 上一页" => Some("next / previous page"),
        "主键 " => Some("primary key "),
        "事件 {}" => Some("event {}"),
        "仅 1 个结果标签" => Some("only 1 result tab"),
        "仅保留第一列（已记住）" => Some("kept only the first column (remembered)"),
        "仅表格浏览支持删除行" => Some("delete rows is only supported in table browsing"),
        "仅表格浏览支持快速插入" => Some("quick insert is only supported in table browsing"),
        "仅表格浏览支持排序" => Some("sorting is only supported in table browsing"),
        "仅表格浏览支持过滤" => Some("filtering is only supported in table browsing"),
        "仅首列" => Some("first only"),
        "任一语句失败则整体回滚；Enter 后立即执行" => Some("any statement failure rolls back everything; runs immediately on Enter"),
        "例: city = 'Beijing'（留空回车 = 清除）" => Some("e.g. city = 'Beijing' (empty + Enter = clear)"),
        "侧栏" => Some("sidebar"),
        "保存" => Some("save"),
        "保存片段 {} …" => Some("Saving snippet {} …"),
        "保存连接…" => Some("Saving connection…"),
        "保留" => Some("keep"),
        "先按 / 搜索结果，再用 n/N 跳转命中" => Some("search first with /, then jump with n/N"),
        "先选中一张表" => Some("select a table first"),
        "先选择连接" => Some("select a connection first"),
        "全选" => Some("all"),
        "全部 {} 列已适配" => Some("all {} columns fit"),
        "共 {} 行" => Some("{} rows"),
        "关" => Some("off"),
        "关闭" => Some("close"),
        "切库" => Some("switch db"),
        "切换" => Some("switch"),
        "切换到 {} …" => Some("Switching to {} …"),
        "切换到 {} 并打开 {} …" => Some("Switching to {} and opening {} …"),
        "切换命令模式 SQL → Redis → MongoDB" => Some("Switch command mode SQL → Redis → MongoDB"),
        "切换数据库 → {}" => Some("Switch database → {}"),
        "切换数据库（快捷）" => Some("Switch database (shortcut)"),
        "切换本次会话的结果标签" => Some("Switch result tab for this session"),
        "列" => Some("column"),
        "列   " => Some("col   "),
        "列 {}{}-{}/{}" => Some("cols {}{}-{}/{}"),
        "列显隐浮层（空格勾选 / a 全选 / x 仅首列，按 库.表 记住）" => Some("Column visibility (Space toggle / a all / x first only, remembered per db.table)"),
        "列显隐：空格勾选显示的列（按 库.表 记住，跨会话）" => Some("Column visibility: Space toggles shown columns (remembered per db.table, across sessions)"),
        "列窗口横滚一列（任意区域，按住连滚）" => Some("Scroll the column window by one (any pane, hold to repeat)"),
        "删行" => Some("delete row"),
        "删除当前行 → 确认后执行" => Some("Delete current row → confirm before running"),
        "删除确认 · Enter 执行 · Esc 取消" => Some("Delete confirmation · Enter execute · Esc cancel"),
        "刷新" => Some("refresh"),
        "刷新 / 关闭" => Some("refresh / close"),
        "刷新数据库列表…" => Some("Refreshing database list…"),
        "加入批量" => Some("add to batch"),
        "加入批量队列（Ctrl-S 打包事务提交）" => Some("Add to batch queue (Ctrl-S commits as one transaction)"),
        "加载 SQL 片段…" => Some("Loading SQL snippets…"),
        "加载 {} 第 {} 页…" => Some("Loading {} page {}…"),
        "加载 {} 结构…" => Some("Loading {} structure…"),
        "加载 {} 表…" => Some("Loading {} tables…"),
        "加载 {}.{} 数据…" => Some("Loading {}.{} data…"),
        "加载更多… (上限 {} 行)" => Some("Load more… (cap {} rows)"),
        "加载连接…" => Some("Connecting…"),
        "勾选" => Some("toggle"),
        "升序" => Some("ascending"),
        "单元格光标（列窗口跟随）" => Some("Cell cursor (column window follows)"),
        "历史" => Some("history"),
        "历史（首行 / 末行）" => Some("History (first / last line)"),
        "取消" => Some("cancel"),
        "取消编辑" => Some("Cancel edit"),
        "可空" => Some("nullable"),
        "启动时显示鼠标事件浮层（滑动无效时排查终端编码）" => Some("Show a mouse-event overlay at startup (diagnose terminal encoding when swiping fails)"),
        "回到侧栏" => Some("back to sidebar"),
        "复制" => Some("duplicate"),
        "复制INSERT" => Some("copy INSERT"),
        "复制当前行为 INSERT 语句（OSC52 + 文件兜底）" => Some("Copy current row as an INSERT statement (OSC52 + file fallback)"),
        "复制连接 {} · 改参数后 Enter 保存" => Some("Duplicate connection {} · edit fields then Enter to save"),
        "复制连接（预填表单）" => Some("Duplicate connection (prefilled form)"),
        "字段" => Some("field"),
        "字段 ↔ DDL（表结构）" => Some("fields ↔ DDL (table structure)"),
        "完整单元格（任意模式）" => Some("full cell (any mode)"),
        "导出当前结果为 CSV（$HOME）" => Some("Export current result as CSV ($HOME)"),
        "将删除 1 行（主键 {}）" => Some("1 row will be deleted (primary key {})"),
        "将生成的 SQL 转入编辑器微调" => Some("Move the generated SQL into the editor for tweaking"),
        "已保存: {} ({})" => Some("Saved: {} ({})"),
        "已刷新 {} 个数据库" => Some("Refreshed {} databases"),
        "已加入批量队列（{} 条）· Ctrl-S 打包提交 · Ctrl-X 清空" => Some("Added to batch queue ({} items) · Ctrl-S commit · Ctrl-X clear"),
        "已取消" => Some("Cancelled"),
        "已取消收藏" => Some("Save cancelled"),
        "已取消编辑" => Some("Edit cancelled"),
        "已取消过滤" => Some("Filter cancelled"),
        "已展开{}" => Some("expanded {}"),
        "已截断" => Some("truncated"),
        "已收起{}" => Some("collapsed {}"),
        "已显示全部列（已记住）" => Some("All columns shown (remembered)"),
        "已清空批量队列（{} 条）" => Some("Batch queue cleared ({} items)"),
        "已清除结果搜索" => Some("Result search cleared"),
        "已清除表过滤 · {} 个表/视图" => Some("Table filter cleared · {} tables/views"),
        "已经是最后一页" => Some("already on the last page"),
        "已经是第一页" => Some("already on the first page"),
        "已转入编辑器微调 · Ctrl-J 执行" => Some("Moved into the editor · Ctrl-J to run"),
        "已达上限 {} 行，请用 WHERE / LIMIT 缩小查询" => Some("Reached the {} row cap; narrow the query with WHERE / LIMIT"),
        "帮助" => Some("Help"),
        "应用" => Some("apply"),
        "底部进度条" => Some("bottom bar"),
        "开" => Some("on"),
        "强制 NULL 仅用灰色，不依赖终端斜体" => Some("Force NULL to grey only, without relying on terminal italics"),
        "当前列窗口位置 · 点击可跳转" => Some("Current column window position · click to jump"),
        "当前无过滤条件" => Some("no filter active"),
        "当前视图不支持列选择" => Some("column selection is not supported in this view"),
        "影响 {} 行" => Some("{} rows affected"),
        "循环切换区域（侧栏 → 编辑器 → 结果）" => Some("Cycle panes (sidebar → editor → results)"),
        "快速插入 → diff 确认后执行" => Some("Quick insert → confirm the diff before running"),
        "总数未知" => Some("total unknown"),
        "手动" => Some("manual"),
        "打开 DBX 存储文件失败 ({}): {}\n(可用 DBX_DATA_DIR 指定目录，或把 dbx.db 文件路径作为第一个位置参数传入)" => Some("Failed to open the DBX storage file ({}): {}\n(set DBX_DATA_DIR, or pass the dbx.db file path as the first positional argument)"),
        "执行" => Some("execute"),
        "执行中…" => Some("Running…"),
        "执行当前 SQL" => Some("Run current SQL"),
        "执行（SQL 全文可见）" => Some("Execute (full SQL visible)"),
        "执行（UPDATE / INSERT，SQL 全文可见）" => Some("Execute (UPDATE / INSERT, full SQL visible)"),
        "批量 {} 待提交" => Some("batch {} pending"),
        "批量事务：{} 条修改将在同一个 BEGIN … COMMIT 中执行" => Some("Batch transaction: {} changes will run in one BEGIN … COMMIT"),
        "批量提交确认（{} 条）· Enter 执行 · Esc 取消" => Some("Confirm batch commit ({} items) · Enter execute · Esc cancel"),
        "批量队列为空（编辑时按 Ctrl-T 加入）" => Some("Batch queue is empty (press Ctrl-T while editing to add)"),
        "把编辑器里的 SQL 收藏为片段（写入 DBX saved_sql_files）" => Some("Save the editor's SQL as a snippet (writes DBX saved_sql_files)"),
        "折叠 / 展开连接列表" => Some("Collapse / expand the connection list"),
        "按 {} {}{}" => Some("by {} {}{}"),
        "按当前列升 / 降序" => Some("Toggle ascending / descending on the current column"),
        "换模式" => Some("switch mode"),
        "换行" => Some("newline"),
        "提交 / 清空批量队列" => Some("Commit / clear the batch queue"),
        "插入" => Some("insert"),
        "插入 {} → Enter 确认执行 · Esc 取消 · Ctrl-V 转编辑器 · Ctrl-T 加入批量" => Some("Insert {} → Enter to confirm · Esc cancel · Ctrl-V to editor · Ctrl-T add to batch"),
        "插入层 v / b" => Some("insert layer v / b"),
        "插入编辑器" => Some("insert into editor"),
        "搜索" => Some("search"),
        "搜索「{}」· 0 行命中" => Some("Search \"{}\" · 0 rows matched"),
        "搜索「{}」· {} 行命中" => Some("Search \"{}\" · {} rows matched"),
        "搜索「{}」· {} 行命中 · n/N 跳转 · Esc 清除" => Some("Search \"{}\" · {} rows matched · n/N jump · Esc clear"),
        "搜索「{}」· 命中 {}/{}" => Some("Search \"{}\" · hit {}/{}"),
        "搜索命中时：下 / 上一个命中（否则 n 翻页）" => Some("With search hits: next / previous hit (otherwise n pages)"),
        "搜索本页结果行…" => Some("Type to search result rows…"),
        "搜索结果行（输入即筛选，Enter 保留，Esc 清除）" => Some("Search result rows (type to filter, Enter keep, Esc clear)"),
        "操作超时（{}s）· 服务器无响应或网络中断，请检查连接后用 d 重连" => Some("Operation timed out ({}s) · server not responding or network down; check the connection and press d to reconnect"),
        "收藏" => Some("save"),
        "收起 / 展开当前焦点区域" => Some("Collapse / expand the focused pane"),
        "收起结果 / 关闭浮层" => Some("Collapse results / close overlay"),
        "数据库列表（浮层内 r 刷新）" => Some("Database list (r refreshes inside the overlay)"),
        "整屏滚动，跨页衔接" => Some("Scroll a full screen, carrying across pages"),
        "整行详情（紧凑列模式）/ 完整单元格" => Some("Full row details (compact mode) / full cell"),
        "整行详情（纵向，含隐藏列）" => Some("Full row details (vertical, including hidden columns)"),
        "新增一行到 {}.{}" => Some("Insert a row into {}.{}"),
        "新建" => Some("new"),
        "新建连接" => Some("New connection"),
        "无可补全项（前缀「{}」）" => Some("No completions (prefix \"{}\")"),
        "无法从当前结果确定表名（仅表格浏览与含 FROM 的查询支持 y）" => Some("Cannot determine the table from the current result (y works in table browsing and FROM queries)"),
        "无法列举数据库（{}），仅使用配置库 {}" => Some("Cannot list databases ({}); using the configured database {}"),
        "无法列举数据库（{}），将使用连接默认库" => Some("Cannot list databases ({}); using the connection default"),
        "无表 · Tab 到 SQL 编辑器 · Ctrl-L 切 redis/mongo 命令行" => Some("No tables · Tab to SQL editor · Ctrl-L switch redis/mongo shell"),
        "旧值 " => Some("old value "),
        "显示列 {} · 已记住" => Some("Show column {} · remembered"),
        "显隐" => Some("hide"),
        "最近浏览的 5 张表，Enter 直达（侧栏 t）" => Some("The 5 most recent tables, Enter jumps straight there (sidebar t)"),
        "最近表浮层（Enter 直达）" => Some("Recent tables overlay (Enter jumps)"),
        "最近表直达浮层" => Some("Recent tables overlay"),
        "未发现数据库" => Some("No databases found"),
        "未知类型: {} (mysql / postgres / redis / mongodb …)" => Some("Unknown type: {} (mysql / postgres / redis / mongodb …)"),
        "未知选项: {}" => Some("Unknown option: {}"),
        "未连接" => Some("Not connected"),
        "本帮助" => Some("This help"),
        "横向滚动列（触屏左右滑动 / 拖动）；PC 终端若 Shift+滚轮 无效，用 Ctrl+滚轮 或 Ctrl-G" => Some("Scroll columns horizontally (touch swipe / drag); on PC terminals where Shift+wheel does nothing, use Ctrl+wheel or Ctrl-G"),
        "横滚 关 · 滚轮纵向" => Some("pan off · wheel scrolls rows"),
        "横滚 开" => Some("pan on"),
        "横滚 开 · 滚轮横滚列" => Some("pan on · wheel scrolls columns"),
        "横滚列一列（任意区域，按住连滚）" => Some("Scroll columns by one (any pane, hold to repeat)"),
        "横滚模式（触屏兜底：滚轮/上下滑 = 横滚列）" => Some("Pan mode (touch fallback: wheel / vertical swipe scrolls columns)"),
        "横滚模式：纵向滚轮/上下滑改为横滚列" => Some("Pan mode: vertical wheel / swipe scrolls columns"),
        "没有保存的 SQL 片段（可在 DBX 桌面端保存后复用）" => Some("No saved SQL snippets (save them in the DBX desktop app to reuse)"),
        "没有可切换的数据库" => Some("No database to switch to"),
        "没有可删除的行" => Some("No row to delete"),
        "没有可加载的更多结果（结果未截断）" => Some("No more rows to load (result not truncated)"),
        "没有可复制的行" => Some("No row to copy"),
        "没有可导出的列" => Some("No column to export"),
        "没有可导出的结果" => Some("No result to export"),
        "没有可插入的列" => Some("No column to insert into"),
        "没有可搜索的结果" => Some("No result to search"),
        "没有可选择的列（先打开一张表或执行查询）" => Some("No column to select (open a table or run a query first)"),
        "注释" => Some("comment"),
        "浏览" => Some("browse"),
        "浏览表数据" => Some("Browse table data"),
        "清除" => Some("clear"),
        "清除过滤" => Some("Clear filter"),
        "滚动" => Some("scroll"),
        "点击向左/右翻一屏列（触屏可用）" => Some("Click to pan one screen of columns left/right (touch friendly)"),
        "焦点 SQL" => Some("focus SQL"),
        "焦点 侧栏" => Some("focus sidebar"),
        "焦点 命令" => Some("focus command"),
        "焦点 结果" => Some("focus results"),
        "片段名称不能为空" => Some("Snippet name cannot be empty"),
        "生成的 SQL（Enter 执行）" => Some("Generated SQL (Enter executes)"),
        "留空 = NULL · '文本' = 字符串" => Some("empty = NULL · 'text' = string"),
        "直接聚焦 侧栏 / 编辑器 / 结果" => Some("Focus sidebar / editor / results directly"),
        "直达" => Some("jump"),
        "真正的 SQL NULL：灰色斜体（终端不支持斜体时仅灰色）" => Some("A real SQL NULL: grey italic (grey only when the terminal lacks italics)"),
        "移动表列表" => Some("Move the table list"),
        "空字符串：灰色，带引号的空串，不会与 NULL 混淆" => Some("Empty string: grey, a quoted empty string, never confused with NULL"),
        "第 {} 行 · {} 列" => Some("row {} · col {}"),
        "第 {}/{} 页" => Some("page {}/{}"),
        "类型" => Some("type"),
        "紧凑列" => Some("compact"),
        "紧凑列 {}{}" => Some("compact {}{}"),
        "紧凑列 手动" => Some("compact manual"),
        "紧凑列宽 开 / 关（窄屏默认自动开，按 库.表 记住）" => Some("Compact columns on/off (auto on narrow terminals, remembered per db.table)"),
        "紧凑列宽：窄屏自动共享列宽，宽表尽量一屏放下" => Some("Compact columns: share width on narrow screens so wide tables fit"),
        "结构" => Some("structure"),
        "结果" => Some("results"),
        "结果 {}/{}" => Some("results {}/{}"),
        "结果 ▸ {} 行 · 点击/Ctrl-W 展开" => Some("results ▸ {} rows · click/Ctrl-W expand"),
        "结果区" => Some("results pane"),
        "结果搜索已清除" => Some("Result search cleared"),
        "结果被截断时加载更多行" => Some("Load more rows when the result is truncated"),
        "编辑" => Some("edit"),
        "编辑 {} → Enter 确认执行 · Esc 取消 · Ctrl-V 转编辑器 · Ctrl-T 加入批量" => Some("Edit {} → Enter to confirm · Esc cancel · Ctrl-V to editor · Ctrl-T add to batch"),
        "编辑/保存" => Some("edit/save"),
        "编辑单元格 → diff 确认后执行" => Some("Edit cell → confirm the diff before running"),
        "编辑器" => Some("editor"),
        "编辑器为空：先写 SQL 再收藏" => Some("Editor is empty: write SQL before saving"),
        "耗时" => Some("elapsed"),
        "聚焦 SQL 编辑器" => Some("Focus the SQL editor"),
        "脚本 {} 条" => Some("script {} items"),
        "脚本 · {} 条语句 · 影响 {} 行 · {} 错误 · Enter 看结果" => Some("script · {} statements · {} rows affected · {} errors · Enter view results"),
        "脚本列表不支持搜索（先 Enter 进入某条语句的结果）" => Some("Script list does not support search (press Enter to open a statement's result first)"),
        "脚本列表没有可复制的行（先 Enter 进入某条语句的结果）" => Some("Script list has no row to copy (press Enter to open a statement's result first)"),
        "自动" => Some("auto"),
        "自动折叠 关" => Some("auto-collapse off"),
        "自动折叠 开" => Some("auto-collapse on"),
        "自动折叠 开 / 关（开=非焦点栏收起）" => Some("Auto-collapse on / off (on = unfocused panes collapse)"),
        "自动折叠：关 · 所有栏展开（Ctrl-A 开启）" => Some("Auto-collapse: off · all panes expanded (Ctrl-A to enable)"),
        "自动折叠：开 · 非焦点栏收起（Ctrl-A 关闭）" => Some("Auto-collapse: on · unfocused panes collapsed (Ctrl-A to disable)"),
        "至少保留一列" => Some("keep at least one column"),
        "行" => Some("row"),
        "行 {}/{}" => Some("row {}/{}"),
        "行光标（到边自动翻页）" => Some("Row cursor (auto page at the edges)"),
        "补全" => Some("complete"),
        "补全上下文" => Some("Completion context"),
        "表" => Some("table"),
        "表名. 后只补该表列名；FROM/JOIN 后优先表名；WHERE/ON 后优先列名" => Some("After table.: only that table's columns; after FROM/JOIN: tables first; after WHERE/ON: columns first"),
        "表结构尚未加载，稍后重试" => Some("Table structure not loaded yet, try again later"),
        "表结构视图不支持搜索" => Some("Structure view does not support search"),
        "表结构视图没有可复制的数据行" => Some("Structure view has no data row to copy"),
        "表结构（字段 + DDL）" => Some("Table structure (fields + DDL)"),
        "详情" => Some("details"),
        "语句" => Some("statement"),
        "语法: = != <> > < >= <= LIKE IN BETWEEN IS NULL · AND/OR · 字符串单引号" => Some("Syntax: = != <> > < >= <= LIKE IN BETWEEN IS NULL · AND/OR · single-quoted strings"),
        "转编辑器" => Some("to editor"),
        "转编辑器 / 加入批量（等价 Ctrl-V / Ctrl-T）" => Some("To editor / add to batch (same as Ctrl-V / Ctrl-T)"),
        "输入以搜索结果行…" => Some("Type to search result rows…"),
        "过滤" => Some("filter"),
        "过滤: {}" => Some("filter: {}"),
        "过滤「{}」· {}/{} 个表 · Esc 清除" => Some("Filter \"{}\" · {}/{} tables · Esc clear"),
        "过滤已清除" => Some("Filter cleared"),
        "过滤表名（输入即筛选，Enter 保留，Esc 清除）" => Some("Filter tables (type to filter, Enter keep, Esc clear)"),
        "运行" => Some("run"),
        "返回" => Some("back"),
        "返回连接选择" => Some("Back to connection picker"),
        "还没有浏览过表" => Some("No tables browsed yet"),
        "还没有表可过滤" => Some("No tables to filter"),
        "连接" => Some("connect"),
        "连接 {} ({})…" => Some("Connecting {} ({})…"),
        "退出" => Some("quit"),
        "选择" => Some("select"),
        "选择 / 插入到编辑器" => Some("Select / insert into editor"),
        "选择 / 连接" => Some("Select / connect"),
        "选择连接" => Some("select connection"),
        "钉住 / 取消首列" => Some("Pin / unpin the first column"),
        "键" => Some("key"),
        "附加排序键（多列排序）" => Some("Append sort key (multi-column sort)"),
        "降序" => Some("descending"),
        "隐藏列 {}" => Some("hidden columns {}"),
        "隐藏列 {} · 已记住" => Some("Hide column {} · remembered"),
        "首列已取消钉住 · z 钉住" => Some("First column unpinned · z to pin"),
        "首列已钉住 · z 取消" => Some("First column pinned · z to unpin"),
        "首行 / 末行" => Some("First / last line"),
        "默认值" => Some("default"),
        "（附加排序键）" => Some("(append sort key)"),
        "🔍「{}」{} 命中 · " => Some("🔍 \"{}\" {} hits · "),
        "  DBX_STORE  dbx.db 文件或其所在目录（默认：DBX_DATA_DIR 或平台默认位置）" => Some("  DBX_STORE  path to dbx.db or its directory (default: DBX_DATA_DIR or the platform default)"),
        "  -h, --help     显示本帮助" => Some("  -h, --help     show this help"),
        "  -V, --version  显示版本" => Some("  -V, --version  show version"),
        "DBX 的终端界面" => Some("terminal UI for DBX"),
        "参数" => Some("Arguments"),
        "文档" => Some("Docs"),
        "选项" => Some("Options"),
        "用法" => Some("Usage"),
        " · 已截断" => Some(" · truncated"),
        " · 更多" => Some(" · more"),
        "（暂不支持的类型）" => Some("(unsupported type)"),
        "永不过期" => Some("no expiry"),
        "不存在" => Some("missing"),
        "重新扫描 keys…" => Some("rescanning keys…"),
        "先选中一个 key" => Some("select a key first"),
        "例: app:*（留空回车 = 全部 *）" => Some("e.g. app:* (blank Enter = all *)"),
        "key 匹配模式（SCAN MATCH）" => Some("key match pattern (SCAN MATCH)"),
        "秒数（-1 = 持久化，0 = 立即删除）" => Some("seconds (-1 = persist, 0 = delete now)"),
        "该类型暂不支持直接编辑，可用命令行修改" => Some("this type is not editable here; use the console"),
        "DEL 不可撤销，Enter 后立即执行" => Some("DEL cannot be undone; runs immediately on Enter"),
        "JSON 过滤，例: {\"age\": {\"$gt\": 30}}（留空 = 全部）" => Some("JSON filter, e.g. {\"age\": {\"$gt\": 30}} (blank = all)"),
        "Enter 执行 · Esc 取消" => Some("Enter run · Esc cancel"),
        "确认写入 · Enter 执行 · Esc 取消" => Some("Confirm write · Enter run · Esc cancel"),
        "匹配模式" => Some("match pattern"),
        "查看值" => Some("view value"),
        "更多" => Some("more"),
        "重扫" => Some("rescan"),
        "逻辑库" => Some("logical DB"),
        "命令台" => Some("console"),
        "重命名" => Some("rename"),
        "删 key" => Some("delete key"),
        "翻页" => Some("page"),
        "JSON 过滤" => Some("JSON filter"),
        "无 key · Tab 到命令台 · / 匹配模式 · r 重扫" => Some("no key · Tab console · / pattern · r rescan"),
        "↑↓ 选 key · Enter 查看值 · n 更多 · / 匹配模式\nTab 到命令台 · Ctrl-L 切换模式" => Some("↑↓ key · Enter view · n more · / pattern\nTab console · Ctrl-L switch mode"),
        " 文档 " => Some(" Documents "),
        "/ 匹配模式（SCAN MATCH）" => Some("/ match pattern (SCAN MATCH)"),
        "  n 加载更多…" => Some("  n load more…"),
        "  （无匹配 key）" => Some("  (no matching key)"),
        "SCAN MATCH 模式，例 app:* · 支持 * ? []" => Some("SCAN MATCH pattern, e.g. app:* · supports * ? []"),
        "秒数；-1 = 持久化，0 = 立即删除" => Some("seconds; -1 = persist, 0 = delete now"),
        "新 key 名（已存在的 key 会被覆盖）" => Some("new key name (an existing key is overwritten)"),
        "新的 string 内容（支持多行）" => Some("new string body (multi-line ok)"),
        "新的 hash 字段值" => Some("new hash field value"),
        " MongoDB 过滤 (JSON) · Enter 应用 · Esc 取消 · 留空清除 " => Some(" MongoDB filter (JSON) · Enter apply · Esc cancel · blank clears "),
        "运算符: $eq $gt $lt $in $regex $exists · 留空 = 全部" => Some("operators: $eq $gt $lt $in $regex $exists · blank = all"),
        "{} 字节" => Some("{} bytes"),
        "{} 个元素" => Some("{} elements"),
        "{} 个成员" => Some("{} members"),
        "{} 个字段" => Some("{} fields"),
        "{} 条" => Some("{} entries"),
        "{} 个文档" => Some("{} documents"),
        "{} 个索引" => Some("{} indexes"),
        "加载 {} keys…" => Some("loading {} keys…"),
        "{} 个 key · 已全部加载" => Some("{} keys · all loaded"),
        "{} 个 key · 已加载 {} · n 加载更多" => Some("{} keys · {} loaded · n load more"),
        "{}.{} · 第 {} 页 · {} 个文档 · 共 {} · n/p 翻页 · f 过滤" => Some("{}.{} · page {} · {} documents · {} total · n/p page · f filter"),
        "{} 索引 · {} · Esc 返回" => Some("{} indexes · {} · Esc back"),
        "加载 {} 索引…" => Some("loading {} indexes…"),
        "加载 key {}…" => Some("loading key {}…"),
        "加载 {} 文档…" => Some("loading {} documents…"),
        "设置 TTL · {}" => Some("Set TTL · {}"),
        "重命名 key · {}" => Some("Rename key · {}"),
        "编辑 string · {}" => Some("Edit string · {}"),
        "编辑 hash 字段 · {} · {}" => Some("Edit hash field · {} · {}"),
        "redis db {} · {} keys · d 切换" => Some("redis db {} · {} keys · d switch"),
        "执行 {}…" => Some("running {}…"),
        "✓ 已复制（{} 字符）· 兜底 {}" => Some("✓ copied ({} chars) · fallback {}"),
        "✓ 已复制（{} 字符）· OSC52 剪贴板" => Some("✓ copied ({} chars) · OSC52 clipboard"),
        "将删除 key {}（不可撤销）" => Some("will delete key {} (cannot be undone)"),
        "匹配模式 → {}" => Some("match pattern → {}"),
        "将执行 {}" => Some("will run {}"),
        " {}Redis · {} · {} · TTL {} · {} · e 编辑 x TTL m 重命名 Del 删除 " => Some(" {}Redis · {} · {} · TTL {} · {} · e edit x TTL m rename Del delete "),
        "共 {} 个" => Some("{} total"),
        " · 过滤 {}" => Some(" · filter {}"),
        "Enter 确认 · Esc 取消" => Some("Enter confirm · Esc cancel"),
        " · 更多（n 加载）" => Some(" · more (n to load)"),
        "已全部加载" => Some("all loaded"),
        "加载更多…" => Some("loading more…"),
        "已加载 {} 项" => Some("{} items loaded"),
        "已加载 {} 项 · 全部" => Some("{} items loaded · all"),
        "已加载 {} 项 · n 继续" => Some("{} items loaded · n to continue"),
        "— Redis key 浏览器 —" => Some("— Redis key browser —"),
        "— MongoDB 文档浏览器 —" => Some("— MongoDB document browser —"),
        "选择 key / 查看 value" => Some("select key / view value"),
        "编辑 SCAN MATCH 模式（留空 = 全部）" => Some("edit the SCAN MATCH pattern (blank = all)"),
        "加载下一 SCAN 页" => Some("load the next SCAN page"),
        "以当前模式重扫" => Some("rescan with the current pattern"),
        "切换逻辑 db" => Some("switch logical DB"),
        "编辑 string·hash 字段 / TTL / 重命名 / 删除 key（均确认）" => Some("edit string/hash field / TTL / rename / delete key (all confirmed)"),
        "大集合继续加载 200 项" => Some("keep loading 200 more items of a large collection"),
        "复制当前行为 TSV" => Some("copy the focused row as TSV"),
        "浏览 collection 文档（JSON 网格）" => Some("browse collection documents (JSON grid)"),
        "文档翻页" => Some("page through documents"),
        "JSON 过滤（如 {\"age\": {\"$gt\": 30}}，留空清除）" => Some("JSON filter (e.g. {\"age\": {\"$gt\": 30}}; blank clears)"),
        "查看 collection 索引" => Some("view collection indexes"),
        // ── R21: Redis batch key operations ──
        "已选 {}" => Some("{} selected"),
        "已选 {} 个 key" => Some("{} keys selected"),
        "已全选 {} 个 key" => Some("selected all {} keys"),
        "已清除选择" => Some("selection cleared"),
        "{} · {} keys · 已选 {} " => Some("{} · {} keys · {} selected "),
        "✓ 已复制 {} 个 key 名 · 兜底 {}" => Some("✓ copied {} key names · fallback {}"),
        "✓ 已复制 {} 个 key 名 · OSC52 剪贴板" => Some("✓ copied {} key names · OSC52 clipboard"),
        "批量执行 {} 条命令…" => Some("running {} batch commands…"),
        "批量完成 {}/{}：{}" => Some("batch finished {}/{}: {}"),
        "✓ 批量完成 {}/{} 条命令" => Some("✓ batch finished {}/{} commands"),
        "将影响 {} 个 key（模式 {}）" => Some("affects {} keys (pattern {})"),
        "Enter 后按顺序执行，不可撤销" => Some("runs in order on Enter; cannot be undone"),
        "批量确认 · Enter 执行 · Esc 取消" => Some("Batch confirm · Enter run · Esc cancel"),
        "选中 {} 个 key 超过单页上限 {}，请分批操作（space 取消部分选择）" => Some("{} keys selected exceeds the {} per-page cap; split the batch (space to unselect)"),
        "批量删除 {} 个 key" => Some("batch delete {} keys"),
        "将批量删除 {} 个 key（模式 {}）" => Some("will batch delete {} keys (pattern {})"),
        "… 其余 {} 条命令" => Some("… {} more commands"),
        "共 {} 个 key · {} 条命令" => Some("{} keys · {} commands total"),
        "批量设置 TTL · {} 个 key" => Some("Batch set TTL · {} keys"),
        "批量设置 TTL={}s · {} 个 key" => Some("batch set TTL={}s · {} keys"),
        "将对 {} 个 key 设置 TTL={}s（模式 {}）" => Some("will set TTL={}s on {} keys (pattern {})"),
        "Enter 后立即执行" => Some("runs immediately on Enter"),
        "TTL 需为整数秒（-1 持久化，0 立即删除）" => Some("TTL must be an integer number of seconds (-1 persist, 0 delete now)"),
        "旧前缀=新前缀，例: app: = new:" => Some("old=prefix new, e.g. app: = new:"),
        "旧前缀=新前缀，例 app: = new:" => Some("old=prefix new, e.g. app: = new:"),
        "格式：旧前缀=新前缀，例 app: = new:" => Some("format: oldprefix=newprefix, e.g. app: = new:"),
        "批量前缀重命名 · {} 个 key" => Some("Batch prefix rename · {} keys"),
        "批量前缀重命名 {} → {} · {} 个 key" => Some("batch prefix rename {} → {} · {} keys"),
        "将重命名 {} 个 key：{} → {}（模式 {}）" => Some("will rename {} keys: {} → {} (pattern {})"),
        "没有 key 匹配该前缀（未改名）" => Some("no key matches that prefix (nothing renamed)"),
        "没有可操作的 key" => Some("no keys to operate on"),
        "勾选 key / 范围选（a 全选已加载）" => Some("toggle / range-select keys (a selects all loaded)"),
        "批量删除 / 设 TTL / 前缀重命名选中 key（均确认）" => Some("batch delete / set TTL / prefix-rename the selected keys (all confirmed)"),
        "复制选中的 key 名（每行一个）" => Some("copy the selected key names (one per line)"),
        "编辑 / 插入 / 删除文档（均确认，_id 不可改）" => Some("edit / insert / delete a document (all confirmed, _id immutable)"),
        "二次确认 · {}" => Some("Re-confirm · {}"),
        "输入 {} 或 YES" => Some("type {} or YES"),
        "二次确认：输入 {} 或 YES" => Some("re-confirm: type {} or YES"),
        "输入不匹配（需 {} 或 YES）" => Some("input does not match (need {} or YES)"),
        "输入 key 数或 YES 以确认删除" => Some("type the key count or YES to confirm deletion"),
        // ── R21: MongoDB document CRUD ──
        "没有可编辑的文档" => Some("no document to edit"),
        "没有可删除的文档" => Some("no document to delete"),
        "JSON 文档（_id 不可修改）" => Some("JSON document (_id is immutable)"),
        "新文档 JSON（省略 _id 则由 MongoDB 生成）" => Some("new document JSON (omit _id to let MongoDB generate it)"),
        "编辑文档 · Ctrl-S 校验并保存 · Esc 取消" => Some("Edit document · Ctrl-S validate & save · Esc cancel"),
        "插入文档 · Ctrl-S 校验并保存 · Esc 取消" => Some("Insert document · Ctrl-S validate & save · Esc cancel"),
        "将删除文档 _id={}（不可撤销）" => Some("will delete document _id={} (cannot be undone)"),
        "删除文档确认 · Enter 执行 · Esc 取消" => Some("Delete document confirm · Enter run · Esc cancel"),
        "JSON 非法：{}" => Some("invalid JSON: {}"),
        "✗ JSON 非法：{}" => Some("✗ invalid JSON: {}"),
        "文档必须是 JSON 对象 { … }" => Some("the document must be a JSON object { … }"),
        "✗ 文档必须是 JSON 对象" => Some("✗ the document must be a JSON object"),
        "将向 {}.{} 插入 1 个文档" => Some("will insert 1 document into {}.{}"),
        "插入确认 · Enter 执行 · Esc 取消" => Some("Insert confirm · Enter run · Esc cancel"),
        "_id 不可修改（请恢复原值）" => Some("_id is immutable (restore the original value)"),
        "✗ _id 不可修改" => Some("✗ _id is immutable"),
        "（没有字段变化）" => Some("(no field changes)"),
        "…（更多字段已省略）" => Some("… (more fields omitted)"),
        "将替换文档 _id={}" => Some("will replace document _id={}"),
        "更新确认（含 diff）· Enter 执行 · Esc 取消" => Some("Update confirm (with diff) · Enter run · Esc cancel"),
        "_id 不可修改 · Ctrl-S 预览 diff 后确认" => Some("_id is immutable · Ctrl-S previews the diff before confirming"),
        "输入 JSON 对象，可省略 _id" => Some("enter a JSON object; _id may be omitted"),
        "Ctrl-S 校验并保存 · Esc 取消 · 方向键移动" => Some("Ctrl-S validate & save · Esc cancel · arrows move"),
        " ✎ 编辑文档 {}.{} " => Some(" ✎ Edit document {}.{} "),
        " ➕ 插入文档 {}.{} " => Some(" ➕ Insert document {}.{} "),
        "批量删" => Some("batch del"),
        "批量TTL" => Some("batch TTL"),
        "批量改名" => Some("batch rename"),
        "删文档" => Some("del doc"),
        "校验并保存" => Some("validate & save"),
        _ => None,
    }
}
